# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "182d30e2dddb04b5dc4543a900536dc5"
name = "loyalty-int-mvp"
handle = "loyalty-int-mvp"
application_url = "https://gibson-claire-yoga-banners.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-f083da00.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://gibson-claire-yoga-banners.trycloudflare.com/auth/callback",
  "https://gibson-claire-yoga-banners.trycloudflare.com/auth/shopify/callback",
  "https://gibson-claire-yoga-banners.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
